eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
server:
  port: 8095
spring:
  application:
    name: api-gateway

#Routing with zuul
zuul:
  routes:
    auth-token-generation:
      path: /v1/authenticate
      serviceId: auth-service
      stripPrefix: false
    auth-token-validation:
      path: /v1/validating-token
      serviceId: auth-service
      stripPrefix: false
    product:
      path: /api/products
      serviceId: product-service
      stripPrefix: false
    productid:
      path: /api/products/*
      serviceId: product-service
      stripPrefix: false
    usercreate:
      path: /v1/users**
      serviceId: user-service
      stripPrefix: false
    userother:
      path: /v1/user
      serviceId: user-service
      stripPrefix: false
    userid:
      path: /v1/users/*
      serviceId: user-service
      stripPrefix: false
  SendErrorFilter:
    error:
      disable: true


