eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
server:
  port: 8095
spring:
  application:
    name: api-gateway

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
#Routing with zuul
zuul:
  sensitiveHeaders:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 120000 # starting the connection
    socket-timeout-millis: 120000  # monitor the continuous incoming data flow
  routes:
    auth-token-generation:
      path: /v1/authenticate
      serviceId: auth-service
      stripPrefix: false
    auth-token-validation:
      path: /v1/validating-token
      serviceId: auth-service
      stripPrefix: false
    product:
      path: /api/products
      serviceId: product-service
      stripPrefix: false
    productid:
      path: /api/products/*
      serviceId: product-service
      stripPrefix: false
    usercreate:
      path: /v1/users**
      serviceId: user-service
      stripPrefix: false
    userother:
      path: /v1/user
      serviceId: user-service
      stripPrefix: false
    userid:
      path: /v1/users/*
      serviceId: user-service
      stripPrefix: false
  SendErrorFilter:
    error:
      disable: true


